<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_motorschuif" Id="{8dff1dda-1eaf-4de2-af1a-82d04b1faa31}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_motorschuif
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{7fee0c1d-bebc-44c9-b133-7feef7fcbd41}" />
    <Folder Name="Properties" Id="{0fd6729b-516d-48d5-bc33-1af661691166}" />
    <Property Name="ActuelePositie" Id="{1e193078-0478-42ae-8b12-3a3217ff5fad}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY ActuelePositie : INT]]></Declaration>
      <Get Name="Get" Id="{bc726eb8-aab8-4aab-a036-a43e484f77ca}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{8b199614-354a-4595-9ad7-26a373538da0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Power" Id="{65b7ad46-9680-4b45-8faa-335489f2bdcb}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD Power : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Quickstop" Id="{889241dd-1070-4625-99b4-91443a7c6e0a}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD Quickstop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SturingRelatievePositie" Id="{1efcbf65-8525-4e77-9d47-7dcd5b87c1ee}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD SturingRelatievePositie : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>