<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_LimitSwitch" Id="{137785a7-15d8-4e79-b5ff-d0d4302269b5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LimitSwitch IMPLEMENTS ITF_LimitSwitch
VAR
    _active : BOOL;      // interne toestand
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{d0ad4a97-693a-4a21-9539-ffb74d92db8e}" />
    <Folder Name="Properties" Id="{2ff26a08-00f7-4465-b1e0-fc1e310ffe81}" />
    <Property Name="Active" Id="{d57d9cc4-66f5-4fe0-b715-e5a24302d021}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY Active : BOOL]]></Declaration>
      <Get Name="Get" Id="{87f8fc36-f9ee-4fa3-92d1-8e80f605c5c8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Active := _active;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{fefa3abf-4913-46fa-a2a1-2386f5a64296}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Update" Id="{cc05bfbb-c495-4816-871a-0533e6f57adc}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD PUBLIC Update : BOOL
VAR_INPUT
	iActive	: BOOL; // TRUE = eindschakelaar aangetikt
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_active := iActive;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>