<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BufferA" Id="{f4348fe5-00a7-44c8-b996-13a856095685}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BufferA
VAR_INPUT
    klep   : ITF_UnitKlep;   // unit-interface
    i_bClk : BOOL;           // command van boven (TRUE = open)
END_VAR

VAR_OUTPUT
    o_bKlepOpen : BOOL;      // status naar boven (TRUE = open)
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Stuur de klep-unit aan
klep.SturingOpen(i_bClk);

// Lees status van klep uit en geef die door naar boven
o_bKlepOpen := klep.Status;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>