<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{69f3564d-4b0f-48c8-af69-b703e93ec4b9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    TestClk : BOOL;      // testbool
    Klep1   : FB_Klep;   // unit
    BufferA : FB_BufferA; // equipment
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[BufferA(
    klep   := Klep1,   // interface van de unit doorgeven
    i_bClk := TestClk  // command van boven (bijv. via HMI)
);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>