<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_DrukKnop" Id="{3ad99ce3-80d4-41bf-94ed-1b26450dad3b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DrukKnop IMPLEMENTS ITF_DrukKnop
VAR
    _pressed : BOOL;   // interne opslag van de knopstatus
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{527a53a8-8344-44f7-b6a0-d8a2c813bcf8}" />
    <Folder Name="Properties" Id="{846eab06-e27a-4433-9703-e167098b28d9}" />
    <Property Name="Pressed" Id="{eb8c14eb-5ca8-4537-8184-62ed2a9337a8}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY PUBLIC Pressed : BOOL]]></Declaration>
      <Get Name="Get" Id="{40c51f60-fc71-45fa-9ac0-e4cc71770d2d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Pressed := _pressed;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{13b8ac60-a39c-4a72-a940-045b7db49b1a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Update" Id="{e32bba49-123e-48c9-aeff-55c8609acc74}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD PUBLIC Update
VAR_INPUT
    iPressed : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_pressed := iPressed;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>