<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_LichtSensor" Id="{48618df0-88e0-405a-a497-d4476e15808e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_LichtSensor IMPLEMENTS ITF_LichtSensor
VAR_INPUT
	I_LichtSensorGeblokkeerd : BOOL; // GEBLOKKEERD = TRUE, DEGEBLOKKEERD = FALSE
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Properties" Id="{74b1a1f4-6d6a-46a3-9528-8b519df6871f}" />
    <Property Name="Geblokkeerd" Id="{36749b5b-00e6-4e3e-9065-1baa35340ccb}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY Geblokkeerd : BOOL
]]></Declaration>
      <Get Name="Get" Id="{bf837c43-026b-4562-886b-732a33b60c5a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Geblokkeerd := I_LichtSensorGeblokkeerd; ]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>